
### create task
POST http://localhost:8081/task-manager/task
Content-Type: application/json

{
    "task-name": "ABC",
    "task-desc": "Task-001"
}

### get task status
GET http://localhost:8081/task-manager/task
#?task-id=1&task-name=abc
Content-Type: application/json

### create task
POST http://localhost:8091/task-processor/task
Content-Type: application/json

{
    "task-id": 1,
    "task-name": "ABC",
    "task-desc": "Task-001",
    "task-status": "CREATED"
}

### get task status
GET http://localhost:8091/task-processor/task
#?task-id=1&task-name=abc
Content-Type: application/json

### get task status stream
GET http://localhost:8091/task-processor/stream
Content-Type: application/json